### ISSUE TITLE
[1.16.4-0.1.2]display errors

### ISSUE THREAD

**Issue by EnterFor** [aurilisdev/Nuclear-Science#2] opened 2021-01-10 06:50 UTC
![image](https://user-images.githubusercontent.com/10114685/104116355-b1f26600-530f-11eb-8352-29c5d8ac6688.png)
forge：35.1.28

**Comment by EnterFor** [comment] 2021-01-10 06:50
And are there any instructions for using it? I don't know how to play it...:)

**Comment by aurilisdev** [comment] 2021-01-10 13:01
What mods are you using?

**Comment by aurilisdev** [comment] 2021-01-10 13:02
If you are using a mod like optifine or any other mods that improve performance in a way that changes graphics, that might screw up rendering for other mods

**Comment by EnterFor** [comment] 2021-01-10 13:03
![image](https://user-images.githubusercontent.com/10114685/104123623-319a2800-5344-11eb-8092-26f1b491a64f.png)
I did not use Optifine, can this picture help you?

**Comment by EnterFor** [comment] 2021-01-10 13:06
You have alerted me, and by what you say, I suspect the ModernUI Mod is responsible.
Do I need to report to its author?

**Comment by aurilisdev** [comment] 2021-01-10 13:07
The performant mod might screw up stuff but i do not know. The mod itself changes alot of the in-game rendering mechanics. Will see if i can recreate the error myself. If i cant recreate the error by just using the same versions of electrodynamics and nuclear science as you are then its definitely one of your mods but i cant be certain. I will tell you shortly if it happens for me when using the same mod versions :)

**Comment by aurilisdev** [comment] 2021-01-10 13:09
Didnt mean to close it hahah

**Comment by aurilisdev** [comment] 2021-01-10 13:13
![image](https://user-images.githubusercontent.com/19689071/104123869-c9e8da80-534d-11eb-8bb2-fbe151a4c5d6.png)
I cant seem to recreate the error in 1.16 with only those two mods. Think its either ModernUI or Performant. You can try and remove either of them and see if that fixes the error

**Comment by EnterFor** [comment] 2021-01-10 13:17
Oh yes, when I delete Modernui, the problem goes away

**Comment by aurilisdev** [comment] 2021-01-10 13:18
Ah then you know what the issue is. If you look in the mod if it has any settings or whatever it is then you might be able to disable what does it and fix it :)

**Closed as completed by aurilisdev** 2021-01-10 13:18 UTC

**Comment by BloCamLimb** [comment] 2021-01-10 14:21
I have Modern UI 2.3.4 and Performant 3.30m, but can't reproduce the bug.

**Comment by aurilisdev** [comment] 2021-01-10 14:22
Huh weird. Maybe its a combined bug with the other mdos. Anways @EnterFor check if you are using the most updated versions of those mods and if so check if any other mods might also be conflicting :)

**Comment by EnterFor** [comment] 2021-01-10 14:24
It's a little difficult for me...
I don't have a clue...

**Comment by aurilisdev** [comment] 2021-01-10 14:28
What version of performant are you using?

**Comment by aurilisdev** [comment] 2021-01-10 14:28
Also if you remove performant is the bug still there?

**Comment by EnterFor** [comment] 2021-01-10 14:32
I use Performant 3.30m, which is already the latest version.
In my own client, removing the Modern UI solves this problem. But he installed all without this problem.
I think you are right, it may be caused by other mods.

**Comment by EnterFor** [comment] 2021-01-10 14:34
Thank you anyway~

**Comment by EnterFor** [comment] 2021-01-11 14:01
Hey, here I am, when I added Optifine to the client, the rendering error disappeared, I didn't remove any mods, weird...
By the way... Does this Mod have a brief description? How to play it?  ღ( ´･ᴗ･` )
